#pragma once

#include <array>

// Generated by gen_cube.py
constexpr std::array<float, 144> cubeVertices = {
    -1.0f, -1.0f, -1.0f, 0.0f, 0.0f, -1.0f, 
    1.0f, -1.0f, -1.0f, 0.0f, 0.0f, -1.0f, 
    1.0f, 1.0f, -1.0f, 0.0f, 0.0f, -1.0f, 
    -1.0f, 1.0f, -1.0f, 0.0f, 0.0f, -1.0f, 
    -1.0f, -1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 
    1.0f, -1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 
    1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 
    -1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 
    -1.0f, -1.0f, -1.0f, -1.0f, 0.0f, 0.0f, 
    -1.0f, 1.0f, -1.0f, -1.0f, 0.0f, 0.0f, 
    -1.0f, 1.0f, 1.0f, -1.0f, 0.0f, 0.0f, 
    -1.0f, -1.0f, 1.0f, -1.0f, 0.0f, 0.0f, 
    1.0f, -1.0f, -1.0f, 1.0f, 0.0f, 0.0f, 
    1.0f, 1.0f, -1.0f, 1.0f, 0.0f, 0.0f, 
    1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 
    1.0f, -1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 
    -1.0f, -1.0f, -1.0f, 0.0f, -1.0f, 0.0f, 
    1.0f, -1.0f, -1.0f, 0.0f, -1.0f, 0.0f, 
    1.0f, -1.0f, 1.0f, 0.0f, -1.0f, 0.0f, 
    -1.0f, -1.0f, 1.0f, 0.0f, -1.0f, 0.0f, 
    -1.0f, 1.0f, -1.0f, 0.0f, 1.0f, 0.0f, 
    1.0f, 1.0f, -1.0f, 0.0f, 1.0f, 0.0f, 
    1.0f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 
    -1.0f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 
};

constexpr std::array<unsigned int, 36> cubeIndices = {
    0, 2, 1, 2, 0, 3, 4, 5, 6, 6, 7, 4, 
    8, 10, 9, 10, 8, 11, 12, 13, 14, 14, 15, 12, 
    16, 17, 18, 18, 19, 16, 20, 22, 21, 22, 20, 23, 
};

// Aliases for stable names (so both generators provide the same symbols)
constexpr auto sphereVertices = cubeVertices;
constexpr auto sphereIndices = cubeIndices;

// Vertex count: 24 (expected 24)
// Index count : 36 (expected 36)
// Smooth normals: False
